export const NEXT_CHANCE = 'CURRENT_PLAYER';
export const INCREASE_TOTAL_PLAYED = 'INCREASE_TOTAL_PLAYED';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';