export const NEXT_CHANCE = 'CURRENT_PLAYER';
export const RESET_CHANCE = 'RESET_CHANCE';
export const SET_PLAYER = 'SET_PLAYER';

export const INCREASE_TOTAL_PLAYED = 'INCREASE_TOTAL_PLAYED';
export const RESET_TOTAL_PLAYED = 'RESET_TOTAL_PLAYED';
export const SET_TOTAL_PLAYED = 'SET_TOTAL_PLAYED';

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const RESET_BOARD = 'RESET_BOARD';
export const SET_BOARD = 'SET_BOARD';

export const PREVIOUS_CHANCE = 'PREVIOUS_CHANCE';

export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const UPDATE_PLAYERS = "UPDATE_PLAYERS"

export const UPDATE_ONLINE_MODE = "UPDATE_ONLINE_MODE"
export const RESET_ONLINE_MODE = "RESET_ONLINE_MODE"